# Generated by Django 4.2.25 on 2025-10-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
